
package quote;

import java.util.Map;
import java.util.TreeMap;

import javax.jws.WebService;
import javax.xml.ws.BindingType;


/**
 * Really!
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "StockQuotePort", serviceName = "StockQuoteService", targetNamespace = "http://quote/", endpointInterface = "quote.StockQuotePortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class StockQuoteService_StockQuotePortImpl
    implements StockQuotePortType
{

    private Map<String, Double> prices = new TreeMap<>();
    {
        prices.put("IBM", 143.79);
        prices.put("GOOGL", 1209.70);
        prices.put("MSFT", 137.44);
        prices.put("FB", 175.25);
        prices.put("TWTR", 40.22);
    }
    
    public StockQuoteService_StockQuotePortImpl() {
    }

    /**
     * 
     * @param stockName
     * @return
     *     returns double
     */
    public double getStockPrice(String stockName) {
        Double price = prices.get(stockName);
        return price == null ? -1:price;
    }

}
