<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://quote/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/"
		targetNamespace="http://quote/" name="StockQuoteService">
	<message name="GetStockPriceRequest">
		<part name="StockName" type="xsd:string"/>
	</message>
	<message name="GetStockPriceResponse">
		<part name="Price" type="xsd:double"/>
	</message>
	<portType name="StockQuotePortType">
		<operation name="GetStockPrice">
			<input message="tns:GetStockPriceRequest"/>
			<output message="tns:GetStockPriceResponse"/>
		</operation>
	</portType>
	<binding name="StockQuoteBinding" type="tns:StockQuotePortType">
		<soap:binding	style="rpc"
						transport="http://schemas.xmlsoap.org/soap/http"/>
			<operation name="GetStockPrice">
				<soap:operation soapAction="http://stock.org/GetStockPrice"/>
				<input><soap:body use="literal" namespace="http://quote/" /></input>
				<output><soap:body use="literal" namespace="http://quote/" /></output>
			</operation>
		</binding>
	<service name="StockQuoteService">
		<documentation>Really!</documentation>
		<port name="StockQuotePort" binding="tns:StockQuoteBinding">
			<soap:address location="http://stock.org/stock"/>
		</port>
	</service>
</definitions>
