version: '3'
services:
  activemq:
    image: rmohr/activemq:latest
    ports:
      - "8161:8161"
      - "61616:61616"
  broker:
    build: broker
    depends_on:
      - activemq
    environment:
      - HOST=activemq
  auldfella:
    #    build: auldfella
    build: auldfellas
    depends_on:
      - activemq
    environment:
      - HOST=activemq
  dodgydrivers:
    #    build: dodgydrivers
    build: dodgydrivers
    depends_on:
      - activemq
    environment:
      - HOST=activemq
  girlpower:
    #    build: girlpower
    build: girlpower
    depends_on:
      - activemq
    environment:
      - HOST=activemq
  client:
    #    build: girlpower
    build: client
    depends_on:
      - activemq
    environment:
      - HOST=activemq