version: '3'

services:

  broker:
    build: broker
    network_mode: host

  girlpower:
    build: girlpower
    network_mode: host
    depends_on:
      - broker

  auldfellas:
    build: auldfellas
    network_mode: host
    depends_on:
      - broker

  dodgydrivers:
    build: dodgydrivers
    network_mode: host
    depends_on:
      - broker

  client:
    build: client
    network_mode: host
    depends_on:
      - broker
      - girlpower
      - auldfellas
      - dodgydrivers