
package quote;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StockQuotePortType", targetNamespace = "http://quote/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface StockQuotePortType {


    /**
     * 
     * @param stockName
     * @return
     *     returns double
     */
    @WebMethod(operationName = "GetStockPrice", action = "http://stock.org/GetStockPrice")
    @WebResult(name = "Price", partName = "Price")
    public double getStockPrice(
        @WebParam(name = "StockName", partName = "StockName")
        String stockName);

}
